// <auto-generated />
using ECommerce.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ECommerce.Infrastructure.Migrations
{
    [DbContext(typeof(ECommerceDbContext))]
    [Migration("20250728075404_InitialSetup")]
    partial class InitialSetup
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.18")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ECommerce.Domain.CartItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.ToTable("CartItems");
                });

            modelBuilder.Entity("ECommerce.Domain.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "16-inch MacBook Pro with M3 Max chip, 64GB RAM, 2TB SSD.",
                            ImageUrl = "https://www.istore.com.ng/cdn/shop/files/MacBook_Pro_16_in_M3_Pro_Max_Space_Black_PDP_Image_Position-1__WWEN_de97454c-5c57-46f3-9e95-52ae7c896d93_5000x.jpg?v=1700852370",
                            Name = "MacBook Pro M3 Max",
                            Price = 3999.99m
                        },
                        new
                        {
                            Id = 2,
                            Description = "6.7-inch Super Retina XDR display, A17 Pro, 256GB, Natural Titanium.",
                            ImageUrl = "https://store.storeimages.cdn-apple.com/4668/as-images.apple.com/is/iphone-15-pro-finish-select-202309-6-1inch?wid=5120&hei=2880&fmt=jpeg&qlt=80&.v=1692923760803",
                            Name = "iPhone 15 Pro Max",
                            Price = 1199.00m
                        },
                        new
                        {
                            Id = 3,
                            Description = "13-inch Ultra Retina XDR display, M4 chip, 512GB, Wi-Fi.",
                            ImageUrl = "https://cdsassets.apple.com/live/7WUAS350/images/tech-specs/ipad-pro-11-inch-13-inch.png",
                            Name = "iPad Pro 13-inch (M4)",
                            Price = 1499.00m
                        },
                        new
                        {
                            Id = 4,
                            Description = "Spatial audio, Active Noise Cancellation, MagSafe case with USB-C.",
                            ImageUrl = "https://imgs.search.brave.com/uMYM55DOgxnoSqUUJy99WtLQNhH2RQ1I6HqPeAkGdag/rs:fit:860:0:0:0/g:ce/aHR0cHM6Ly9tLm1l/ZGlhLWFtYXpvbi5j/b20vaW1hZ2VzL0kv/NDFlbENNWHdha0wu/anBn",
                            Name = "AirPods Pro (2nd Gen, USB-C)",
                            Price = 249.00m
                        },
                        new
                        {
                            Id = 5,
                            Description = "49mm Titanium Case with Alpine Loop, S9 SiP, 36-hour battery.",
                            ImageUrl = "https://store.storeimages.cdn-apple.com/1/as-images.apple.com/is/ultra-case-unselect-gallery-1-202409?wid=5120&hei=3280&fmt=p-jpg&qlt=80&.v=aTVJSEliNW9jb25zalBlTm16VmMxcWpkNHRJWDMzcTg3NWRxV0pydTcvSUxMekYrWHVDVjVJT1ZDYVlkUjdVUnc2NytHaDA2aFdROEtrekNxcXV6T3VmenhDNGxXRVM5RSs4RlRpMXdYVWhCUjJHK0dyT0t2cDF1RTlMancyMG8",
                            Name = "Apple Watch Ultra 2",
                            Price = 799.00m
                        },
                        new
                        {
                            Id = 6,
                            Description = "Spatial computer with dual 4K micro‑OLED displays and eye tracking.",
                            ImageUrl = "https://store.storeimages.cdn-apple.com/1/as-images.apple.com/is/vision-pro-gallery-measure-dual-loop-202401?wid=5120&hei=2880&fmt=p-jpg&qlt=95&.v=eDVwb1h3eE5DQmx2RnhFenBtbjB4MCsyQVE0K3V5YzhHbWV1TjRxbDUraFY3K0Z2dldtZ0YyMUJMeFdIdnVxRHF2TWlpSzUzejRCZGt2SjJUNGl1VE5rb3YwRE90eklmVkIwdHovcEFheWc3czE5Q2ZmeDA4OWdkZkN0VGliSzM",
                            Name = "Apple Vision Pro",
                            Price = 3499.00m
                        },
                        new
                        {
                            Id = 7,
                            Description = "Full-range sound with spatial awareness and Siri voice assistant.",
                            ImageUrl = "https://canoonstore.com/wp-content/uploads/2023/08/homepod-select-202210-1024x1024.jpeg",
                            Name = "HomePod (2nd Generation)",
                            Price = 299.00m
                        },
                        new
                        {
                            Id = 8,
                            Description = "Wi-Fi + Ethernet, A15 Bionic chip, supports HDR10+ and Dolby Vision.",
                            ImageUrl = "https://store.storeimages.cdn-apple.com/1/as-images.apple.com/is/apple-tv-4k-hero-select-202210?wid=940&hei=1112&fmt=p-jpg&qlt=95&.v=a3VoZW85YUhreXN3ZFlSUDc3a0tqdU1qeWRTYWRhVU5NM3d6SkhmNzkxTjdKMGdNUjJ3Q0dzSU9tc2pOeGwxbXg4ZHpEbm5XWGdaM3BiNVRDaG55UktNaUdBMSt0VkxKZ2NWelk1alBpUVVXZEdHNUFPR0hYUU12cjI0VlFzM1A",
                            Name = "Apple TV 4K (128GB)",
                            Price = 149.00m
                        });
                });

            modelBuilder.Entity("ECommerce.Domain.CartItem", b =>
                {
                    b.HasOne("ECommerce.Domain.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });
#pragma warning restore 612, 618
        }
    }
}
